// Protocol Buffers 定义文件
// 权限相关的枚举定义
// 定义系统中所有可用的权限类型，使用位运算进行权限组合

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: permission.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 权限枚举
// 定义系统中所有可用的权限类型，每个权限对应一个位标志
// 使用位运算可以方便地进行权限的组合和检查
type Permission int32

const (
	Permission_UNKNOWN      Permission = 0 // 未知权限，默认值
	Permission_ORDER_CREATE Permission = 1 // 创建订单权限 (1 << 0)
	Permission_ORDER_UPDATE Permission = 2 // 更新订单权限 (1 << 1)
	Permission_ORDER_DELETE Permission = 4 // 删除订单权限 (1 << 2)
)

// Enum value maps for Permission.
var (
	Permission_name = map[int32]string{
		0: "UNKNOWN",
		1: "ORDER_CREATE",
		2: "ORDER_UPDATE",
		4: "ORDER_DELETE",
	}
	Permission_value = map[string]int32{
		"UNKNOWN":      0,
		"ORDER_CREATE": 1,
		"ORDER_UPDATE": 2,
		"ORDER_DELETE": 4,
	}
)

func (x Permission) Enum() *Permission {
	p := new(Permission)
	*p = x
	return p
}

func (x Permission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Permission) Descriptor() protoreflect.EnumDescriptor {
	return file_permission_proto_enumTypes[0].Descriptor()
}

func (Permission) Type() protoreflect.EnumType {
	return &file_permission_proto_enumTypes[0]
}

func (x Permission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Permission.Descriptor instead.
func (Permission) EnumDescriptor() ([]byte, []int) {
	return file_permission_proto_rawDescGZIP(), []int{0}
}

var File_permission_proto protoreflect.FileDescriptor

const file_permission_proto_rawDesc = "" +
	"\n" +
	"\x10permission.proto\x12\n" +
	"permission*O\n" +
	"\n" +
	"Permission\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x10\n" +
	"\fORDER_CREATE\x10\x01\x12\x10\n" +
	"\fORDER_UPDATE\x10\x02\x12\x10\n" +
	"\fORDER_DELETE\x10\x04B Z\x1eServerFramework/internal/modelb\x06proto3"

var (
	file_permission_proto_rawDescOnce sync.Once
	file_permission_proto_rawDescData []byte
)

func file_permission_proto_rawDescGZIP() []byte {
	file_permission_proto_rawDescOnce.Do(func() {
		file_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_permission_proto_rawDesc), len(file_permission_proto_rawDesc)))
	})
	return file_permission_proto_rawDescData
}

var file_permission_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_permission_proto_goTypes = []any{
	(Permission)(0), // 0: permission.Permission
}
var file_permission_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_permission_proto_init() }
func file_permission_proto_init() {
	if File_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_permission_proto_rawDesc), len(file_permission_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_permission_proto_goTypes,
		DependencyIndexes: file_permission_proto_depIdxs,
		EnumInfos:         file_permission_proto_enumTypes,
	}.Build()
	File_permission_proto = out.File
	file_permission_proto_goTypes = nil
	file_permission_proto_depIdxs = nil
}
